---
- name: Install packages
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install apt packages
      apt:
        name:
          - vim
          - cron
          - golang-go
          - netcat-traditional
          - ssh
          - openssh-server
        state: present
